import pg from 'pg';
import { readFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
const API = 'http://127.0.0.1:4173';
const db = new pg.Client({ connectionString: 'postgresql://squish@/squish?host=/tmp/pgsock&port=5433' });
await db.connect();
const j = (r) => r.json();
const chief = await j(await fetch(`${API}/api/device`, { method: 'POST' }));
const signin = await fetch(`${API}/api/session`, { method: 'POST', headers: { Authorization: `Bearer ${chief.token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ email: 'chief@example.com', password: 'four random words' }) });
console.log('chief signed in:', signin.status);
await db.query(`update accounts set plus_until = now() + interval '30 days' where email = 'chief@example.com'`);
await db.query(`insert into admin_settings (key, value) values ('gemini_trial', 'on') on conflict (key) do update set value = 'on'`);
const { device: person } = JSON.parse(readFileSync(process.argv[2] + '/wp-who.json', 'utf8'));
const image = 'data:image/png;base64,' + 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==';
const photo = async (token) => j(await fetch(`${API}/api/analyse/photo`, { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ image, slot: 'lunch' }) }));
const show = (label, a) => console.log(label.padEnd(20), '|', a.title ?? a.error, '|', a.nutrients?.calories, 'kcal | trial:', JSON.stringify(a.trial ?? null));
show('admin, Gemini up', await photo(chief.token));
show('ordinary account', await photo(person.token));
execSync('pkill -f "fake-gemin[i].mjs" || true');
await new Promise((r) => setTimeout(r, 500));
show('admin, Gemini down', await photo(chief.token));
await db.query(`update admin_settings set value = 'off' where key = 'gemini_trial'`);
show('admin, switch off', await photo(chief.token));
await db.end();
